export const CLIENT_SELECTED = 'CLIENT_SELECTED';
export const PRODUCTS_SELECTED = 'PRODUCTS_SELECTED';
export const ADD_PRODUCT_QUANTITY = 'ADD_PRODUCT_QUANTITY';
export const UPDATE_TOTAL_ORDER = 'UPDATE_TOTAL_ORDER';
